### ISSUE TITLE
Don't throw exception when no results are returned

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-client#28]
No results matching a query provided is not an exceptional situation. Return empty list instead.

**Comment by dcrissman** [comment]
Because there is no way to know what the generic class T is going to be, the only responsible response is null. Any objections or concerns with that?

**Comment by dcrissman** [comment]
@paterczm in your trouble case, are you expecting a single Object, or an Array/List of Objects?

I ask because it looks to me like upon an empty result set the client is getting the json value '[]', which appears to convert to an empty Array just fine. But it throws a JsonMappingException if it is trying to convert the empty array to an instance of an object.

**Comment by luan-cestari** [comment]
May I take this issue to solve?

**Comment by dcrissman** [comment]
@luan-cestari I did some initial work when I thought this issue was blocking me. Turns out, it wasn't so I didn't finish the changes. Feel free to take what I have and steal from it or throw it out altogether.

I still had a failing unit test when requesting a single Object instance (as opposed to an array), but when the processed response is an empty array node.

**Comment by luan-cestari** [comment]
PR witht he fix https://github.com/lightblue-platform/lightblue-client/pull/70

**Comment by dcrissman** [comment]
This issue has been addressed. Closing.
