### ISSUE TITLE
Jackson exception should not be thrown when non JSON is returned.

### ISSUE THREAD

**Issue by LGordon2** [lightblue-platform/lightblue-client#40]
The lightblue endpoint I was using was down for a bit (due to OpenShift maintenance).  I received an HTML based response, however the stacktrace showed a Jackson parse exception.  Even though this made sense after the fact I feel that it could be handled more gracefully.  Below is an example stacktrace received:

```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@2504577; line: 1, column: 2]
	com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
	com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
	com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:453)
	com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleUnexpectedValue(ReaderBasedJsonParser.java:1386)
	com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:669)
	com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:2926)
	com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2873)
	com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1750)
	com.redhat.lightblue.client.response.LightblueResponse.<init>(LightblueResponse.java:21)
	com.redhat.lightblue.client.http.LightblueHttpClient.callService(LightblueHttpClient.java:119)
	com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:96)
	com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:100)
```

**Comment by luan-cestari** [comment]
@derek63 Hi, I'm not sure if you are working on this issue, in case you are not, may I assign to myself?

**Comment by derek63** [comment]
@luan-cestari I had initially planned to do this for the Ana release, but forgot to unassign myself when we moved it to Bill.  Feel free to pick it up if you'd like.

**Comment by luan-cestari** [comment]
This issues is solved as this line https://github.com/luan-cestari/lightblue-client/blob/9853cb45f955a9a02a92c68155759ff171ec2616/http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java#L165-165 is now handling better the exception that was jut propagated before

**Comment by jewzaam** [comment]
Note 9853cb45f955a9a02a92c68155759ff171ec2616 is part of https://github.com/lightblue-platform/lightblue-client/pull/70

**Comment by luan-cestari** [comment]
Just a brief description what I found when I worked on this issue. It was already fixed long ago. The issue was reported using 1.1.x due the line number in the stacktrace and @paterczm fixed this issue before this issue was opened in the 1.2.x with the following commit https://github.com/lightblue-platform/lightblue-client/blob/cf3956eacc8261e4eb20d16976d128674b40edeb/http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java  and then @dcrissman enhanced it https://github.com/lightblue-platform/lightblue-client/commit/0dce8d3855007449876a7e5a4299c74c680ba248 and now I turned into a runtimeexception on #70 (but I wouldn't say that I solved the issue as it was well handled before I touched)
